use strict;
use warnings;
use Time::HiRes qw(sleep);
use Test::WWW::Selenium;
use Test::More "no_plan";
use Test::Exception;

my $sel = Test::WWW::Selenium->new( host => "localhost", 
                                    port => 4444, 
                                    browser => "*chrome", 
                                    browser_url => "http://localhost:3000/" );

$sel->open_ok("/");
$sel->wait_for_page_to_load_ok("60000");
$sel->open_ok("/");
$sel->click_ok("link=Sign up");
$sel->wait_for_page_to_load_ok("60000");
$sel->type_ok("xpath=//form[\@id='user_new']/dl[1]/dd/input", "jmeter7");
$sel->type_ok("id=user_email", "abc\@aol.com");
$sel->type_ok("xpath=//form[\@id='user_new']/dl[3]/dd/input", "jmeter7");
$sel->type_ok("id=user_password_confirmation", "jmeter7");
$sel->click_ok("id=user_submit");
$sel->wait_for_page_to_load_ok("60000");
$sel->click_ok("link=How it Works");
$sel->click_ok("link=My apps");
$sel->wait_for_page_to_load_ok("60000");
$sel->click_ok("id=step_3");
$sel->wait_for_page_to_load_ok("60000");
$sel->type_ok("id=app_name", "jmeter7-app");
$sel->type_ok("id=app_description", "This is jmeter7 connfu app");
$sel->click_ok("id=app_submit");
$sel->wait_for_page_to_load_ok("60000");
$sel->click_ok("xpath=//div[\@class='table']/a/div/div[2]/p/b");
$sel->wait_for_page_to_load_ok("60000");
$sel->click_ok("xpath=//div[\@id='content']/div[3]");
$sel->click_ok("xpath=//div[\@id='content']/div[4]/div[2]/div");
$sel->click_ok("link=Add channel");
$sel->select_ok("id=channel_type", "RSS");
$sel->type_ok("id=rss_uid", "twitter-uid");
$sel->type_ok("id=rss_uri", "");
$sel->type_ok("id=rss_uid", "rss-uid");
$sel->type_ok("id=rss_uri", "http://www.bbc.co.uk");
$sel->click_ok("id=rss_submit");
$sel->wait_for_page_to_load_ok("60000");
$sel->click_ok("id=app_usage_button");
$sel->click_ok("link=Close");
$sel->click_ok("link=Add channel");
$sel->select_ok("id=channel_type", "Twitter");
$sel->type_ok("id=twitter_uid", "twitter-uid");
$sel->type_ok("id=add_twitter_input", "chiflendotcom");
$sel->type_ok("id=add_twitter_filter_input", "api");
$sel->click_ok("xpath=//div[\@class='account_filters']/a/img");
$sel->click_ok("xpath=//td[\@class='button']/a/img");
$sel->click_ok("id=create_twitter_channel_button");
$sel->wait_for_page_to_load_ok("60000");
$sel->go_back_ok();
$sel->wait_for_page_to_load_ok("60000");
$sel->click_ok("link=Add channel");
$sel->select_ok("id=channel_type", "Voice");
$sel->type_ok("id=voice_uid", "voice-uid");
$sel->select_ok("id=voice_country", "United Kingdom");
$sel->type_ok("id=voice_topic", "Conference powered by connFu.");
$sel->type_ok("id=voice_welcome_message", "Welcome to connFu, you are going to join the conference");
$sel->type_ok("id=voice_rejected_message", "You are not allowed to join this conference");
$sel->click_ok("xpath=//div[\@id='voice_form']//a[.='Cancel']");
$sel->click_ok("link=Add channel");
$sel->select_ok("id=channel_type", "Voice");
$sel->click_ok("id=voice_topic");
$sel->type_ok("id=voice_welcome_message", "Welcome to connFu, you are going to join the conference");
$sel->type_ok("id=voice_rejected_message", "You are not allowed to join this conference");
$sel->click_ok("id=voice_submit");
$sel->wait_for_page_to_load_ok("60000");
$sel->click_ok("xpath=//div[\@id='content']//div[normalize-space(.)='Voice']");
$sel->type_ok("id=whitelisted_name", "jmeter7");
$sel->type_ok("id=whitelisted_phone", "11340927863");
$sel->click_ok("xpath=//div[\@id='whitelist_form']//button[.='Add']");
$sel->click_ok("xpath=//div[\@class='app-create-button']/input");
$sel->wait_for_page_to_load_ok("60000");
$sel->click_ok("xpath=//div[\@id='content']//span[normalize-space(.)='http://www.bbc.co.uk']");
$sel->type_ok("xpath=//form[\@id='edit_rss_4eb3d8fc9c7ec109ba000037']/dl/div/dd/input", "http://www.cnn.com");
$sel->click_ok("xpath=//div[\@class='app-create-button']/input");
$sel->wait_for_page_to_load_ok("60000");
$sel->click_ok("link=Documentation");
$sel->wait_for_page_to_load_ok("60000");
$sel->click_ok("link=Support");
$sel->wait_for_page_to_load_ok("60000");
$sel->click_ok("link=How it Works");
$sel->wait_for_page_to_load_ok("60000");
$sel->click_ok("link=My apps");
$sel->wait_for_page_to_load_ok("60000");
$sel->click_ok("id=step_2");
$sel->wait_for_page_to_load_ok("60000");
$sel->click_ok("link=Support");
$sel->wait_for_page_to_load_ok("60000");
$sel->click_ok("link=My apps");
$sel->wait_for_page_to_load_ok("60000");
$sel->click_ok("id=step_1");
$sel->wait_for_page_to_load_ok("60000");
$sel->click_ok("link=jmeter7");
$sel->wait_for_page_to_load_ok("60000");
$sel->type_ok("id=user_password_confirmation", "jmeter7");
$sel->type_ok("id=user_current_password", "jmeter7");
$sel->type_ok("id=user_password", "jmeter7");
$sel->click_ok("id=user_submit");
$sel->wait_for_page_to_load_ok("60000");
$sel->click_ok("link=Sign out");
$sel->wait_for_page_to_load_ok("60000");
